[package]
name = "wgpu-tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
winit = "0.30.13"
env_logger = "0.11.11"
log = "0.4.33"
wgpu = "30.0.0"
pollster = "0.4.0"
bytemuck = { version = "1.25", features = [ "derive" ] }
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
glam = { version = "0.33.2", features = ["bytemuck"] }
web-time = "1.1.0" #instant tells you to use web-time
rand = "0.10.2"
gltf = {version = "1.4.1", features = ["KHR_materials_emissive_strength", "KHR_materials_ior"]}
guillotiere = "0.7.0"
include_bytes_aligned = "0.2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wgpu = { version = "30.0.0", features = ["webgl"] }
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.76"
web-sys = { version = "0.3.103", features = [ "Document", "Window", "Element"] }
getrandom = { version = "0.3.4", features = ["wasm_js"] }
getrandom_2 = { package = "getrandom", version = "0.4.3", features = ["wasm_js"] }


[lib]
crate-type = ["cdylib", "rlib"]
